export type LegalSection = {
  title: string;
  paragraphs?: string[];
  bullets?: string[];
};

export type LegalDocument = {
  title: string;
  effectiveDate: string;
  introduction: string;
  sections: LegalSection[];
};

const fallbackSupportEmail = "hello@italirpothe.com";

export const supportEmail =
  process.env.NEXT_PUBLIC_CONTACT_EMAIL?.trim() || fallbackSupportEmail;

export const privacyPolicy: LegalDocument = {
  title: "Privacy Policy",
  effectiveDate: "Effective July 23, 2026 · Last updated July 23, 2026",
  introduction:
    "Italir Pothe respects your privacy. This Privacy Policy explains how Italir Pothe collects, uses, stores, protects and shares information when you use the Italir Pothe mobile application, public website, backend services, courses, AI learning tools, messaging, calls, webinars, CV tools, examinations, certificates, rewards, purchases, customer support and related services. In this Privacy Policy, “Italir Pothe,” “we,” “us,” and “our” refer to the operator of the Italir Pothe service.",

  sections: [
    {
      title: "1. Scope of this policy",
      paragraphs: [
        "This Privacy Policy applies to the Italir Pothe mobile application, public website, backend services and related features.",
        "Third-party websites and services linked from Italir Pothe operate under their own privacy policies.",
      ],
      bullets: [
        "Italir Pothe mobile-app users.",
        "Visitors to the Italir Pothe public website.",
        "Registered learners and certificate holders.",
        "Users of courses, quizzes, examinations and practice tools.",
        "Users of AI Tutor, AI voice and AI-assisted CV features.",
        "Users of messages, audio or video calls and webinars.",
        "People who contact support or submit account-deletion requests.",
        "People participating in rewards, purchases or community activities.",
      ],
    },
    {
      title: "2. Information we collect",
      paragraphs: [
        "We collect information that is reasonably necessary to provide, secure, personalize and improve Italir Pothe.",
      ],
    },
    {
      title: "2.1 Account and authentication information",
      paragraphs: [
        "We may collect account and authentication information when you register, sign in, verify your account or use protected services.",
        "We do not store your password as readable plain text.",
      ],
      bullets: [
        "Full name.",
        "Email address.",
        "Phone number.",
        "Password in protected or hashed form.",
        "One-time verification codes and verification status.",
        "Internal user ID and account role.",
        "Email and phone verification status.",
        "Profile photo.",
        "Preferred language.",
        "Learner level.",
        "Account-security and login information.",
        "Authentication tokens and session information.",
      ],
    },
    {
      title: "2.2 Profile and preference information",
      bullets: [
        "Profile photo and profile-photo file information.",
        "App-language selection.",
        "Learning level and learning preferences.",
        "Notification and haptic preferences.",
        "Communication preferences.",
        "Current streak and streak-protection balance.",
        "Other settings you choose to save.",
      ],
    },
    {
      title: "2.3 Learning and course information",
      paragraphs: [
        "We may collect information about how you access and use courses, lessons and learning activities.",
      ],
      bullets: [
        "Course enrollments and purchased courses.",
        "Chapters and lessons accessed.",
        "Video-watching progress.",
        "Audio-listening progress.",
        "Theory or PDF resources opened or completed.",
        "Vocabulary progress and saved words.",
        "Quiz questions, selected answers and results.",
        "Daily challenges and completed tasks.",
        "Time spent on learning activities.",
        "Course-completion percentage.",
        "XP, streaks, achievements and rewards.",
        "Leaderboard position and league information.",
        "Career-track and Survival Italian activity.",
        "Saved learning materials and practice history.",
        "Recommended lessons, focus areas and next steps.",
      ],
    },
    {
      title: "2.4 Examination and certificate information",
      bullets: [
        "Examination-attempt identifiers.",
        "Listening, writing, vocabulary, grammar and speaking answers.",
        "Written examination responses.",
        "Speaking-test audio recordings and transcripts.",
        "Scores and completion results.",
        "Teacher or reviewer comments.",
        "Examination status and review status.",
        "Attempt dates and time taken.",
        "Certificate identifier and reference code.",
        "Learner name shown on a certificate.",
        "Course or examination connected to a certificate.",
        "Certificate issue date, status, PDF and verification information.",
      ],
    },
    {
      title: "2.5 AI Tutor and AI-learning information",
      paragraphs: [
        "AI input may be processed by contracted AI, speech-recognition, speech-generation, transcription and real-time voice providers.",
        "Do not provide government identification numbers, payment-card details, medical information or other highly sensitive information that is unnecessary for language learning.",
      ],
      bullets: [
        "Text prompts and questions.",
        "AI conversation history.",
        "Selected lesson, topic or learning mode.",
        "Writing-assistance requests.",
        "Source language and target language.",
        "Learner level.",
        "Previous mistakes and recent mistake tags.",
        "Learning-memory facts generated from prior interactions.",
        "Level-test questions and answers.",
        "Audio submitted for transcription.",
        "Voice-chat audio streams and transcripts.",
        "AI-generated responses and corrections.",
        "Strengths, weaknesses and recommended focus areas.",
        "Token, voice-time and AI-credit usage.",
        "Session identifiers and technical connection information.",
        "Feedback and reports about AI-generated content.",
        "Screenshots or evidence voluntarily attached to an AI-content report.",
      ],
    },
    {
      title: "2.6 Messages, calls and community information",
      paragraphs: [
        "Live audio and video are transmitted to provide calls.",
        "We retain recordings only where a feature is designed to record information, such as speaking examinations, voice answers or another feature that provides clear notice.",
      ],
      bullets: [
        "Direct messages and message content.",
        "Message timestamps and delivery status.",
        "Conversation identifiers.",
        "Images, audio, documents or other attachments you send.",
        "Sender and recipient identifiers.",
        "Online or presence status.",
        "Call identifiers.",
        "Caller and receiver details.",
        "Audio or video call type.",
        "Call status, duration and timestamps.",
        "Technical channel and connection information.",
        "Blocked-user records.",
        "User reports, report reasons and evidence.",
        "Moderation decisions and safety records.",
      ],
    },
    {
      title: "2.7 Webinar information",
      bullets: [
        "Webinar registration or attendance.",
        "User and participant identifiers.",
        "Display name and profile image.",
        "Join and leave activity.",
        "Chat messages.",
        "Speaker requests and approval status.",
        "Microphone and camera status.",
        "Audio and video streams when participating as a speaker.",
        "Technical connection and channel information.",
        "Reports or moderation information.",
      ],
    },
    {
      title: "2.8 CV and employment-related information",
      paragraphs: [
        "You control what information you include in your CV.",
        "Avoid adding information that is not necessary for your CV.",
      ],
      bullets: [
        "Name and contact details.",
        "Email address and phone number.",
        "Address or location written in your CV.",
        "Professional summary.",
        "Employment history.",
        "Education history.",
        "Skills, qualifications and certifications.",
        "Language ability.",
        "References.",
        "Profile photograph.",
        "Uploaded CV documents or images.",
        "Template, design and formatting preferences.",
        "AI CV-assistant conversations.",
        "Generated CV files and previews.",
      ],
    },
    {
      title: "2.9 Purchase and entitlement information",
      paragraphs: [
        "Google Play processes your payment method.",
        "Italir Pothe does not receive your complete payment-card number, bank-account credentials or Google Play password.",
      ],
      bullets: [
        "Google Play product ID.",
        "Purchase token.",
        "Order or transaction number.",
        "Purchase provider.",
        "Product type.",
        "Price and currency.",
        "Purchase date and status.",
        "Subscription or entitlement status.",
        "Refund, cancellation and chargeback information.",
        "Coupon, referral or promotional information.",
        "Obfuscated account identifier used for transaction verification.",
        "Purchased course, package or digital entitlement.",
        "AI text-token balance.",
        "AI voice-time balance.",
        "CV-credit balance.",
        "Streak-freeze balance.",
        "Reward and other digital balances.",
      ],
    },
    {
      title: "2.10 Rewards and delivery information",
      paragraphs: [
        "This information is used only to process and support reward delivery and related records.",
      ],
      bullets: [
        "Recipient name.",
        "Delivery address.",
        "Country information.",
        "WhatsApp or contact number.",
        "Reward selected or earned.",
        "Shipping status.",
        "Dispatch and delivery information.",
        "Communications related to delivery.",
      ],
    },
    {
      title: "2.11 Contact and support information",
      bullets: [
        "Name.",
        "Email address.",
        "Phone number.",
        "Support subject and message.",
        "Account-deletion request information.",
        "Appeal or complaint details.",
        "Files, screenshots and other evidence you submit.",
        "Communications between you and our support team.",
      ],
    },
    {
      title: "2.12 Device and technical information",
      paragraphs: [
        "The current Android application does not request access to your precise GPS location, address-book contacts, SMS messages or health data.",
      ],
      bullets: [
        "Device or installation identifier.",
        "Firebase push-notification token.",
        "Device platform and operating system.",
        "App version.",
        "Browser type when using the website.",
        "IP address.",
        "Approximate country or region inferred from network or store information.",
        "Language, locale and timezone.",
        "Network and connection information.",
        "API request and response timestamps.",
        "Login, authentication and security events.",
        "Error, diagnostic and performance information.",
        "Feature usage and app-interaction records.",
        "Purchase-verification and fraud-prevention signals.",
      ],
    },
    {
      title: "3. Device permissions",
      paragraphs: [
        "Depending on the feature you use, Italir Pothe may request access to notifications, microphone, camera, photos, selected files and call-related Android functionality.",
        "You may refuse or revoke optional permissions through your device settings.",
        "A feature may not work when its required permission is disabled.",
      ],
      bullets: [
        "Notifications: Used for account and security notices, learning reminders, course or examination updates, messages, incoming-call alerts, webinar reminders, purchases and reward updates.",
        "Microphone: Used for AI voice conversations, speaking practice, speaking examinations, audio messages, calls and webinar speaker participation.",
        "Camera: Used for profile photographs, selected image uploads, video calls and webinar speaker participation.",
        "Photos and selected files: Used for profile photos, evidence, attachments, CV information, messages, reports, generated CVs, certificates and learning PDFs.",
        "Call-related and foreground-service access: Used to maintain incoming or active voice and video calls and display call notifications where permitted by Android.",
      ],
    },
    {
      title: "4. How we use information",
      bullets: [
        "Register, authenticate and secure accounts.",
        "Verify email addresses and phone numbers.",
        "Provide courses, lessons, quizzes and practice features.",
        "Save learning progress and examination results.",
        "Personalize learning content and recommendations.",
        "Provide AI text, voice, translation and writing assistance.",
        "Generate CVs and downloadable documents.",
        "Operate messages, calls and webinars.",
        "Deliver notifications.",
        "Process purchases and verify Google Play transactions.",
        "Grant courses, subscriptions, credits and other digital entitlements.",
        "Issue and verify certificates.",
        "Operate leaderboards, streaks, rewards and daily challenges.",
        "Deliver physical or digital rewards.",
        "Respond to support, reports, appeals and deletion requests.",
        "Detect spam, fraud, cheating, misuse and security threats.",
        "Moderate content and protect users.",
        "Diagnose technical problems.",
        "Measure service performance and improve features.",
        "Enforce our Terms and Conditions.",
        "Comply with legal, tax, accounting and regulatory obligations.",
        "Establish, exercise or defend legal claims.",
      ],
    },
    {
      title: "5. Legal bases for processing",
      paragraphs: [
        "Where laws such as the GDPR apply, we rely on one or more lawful bases for processing.",
        "Performance of a contract may apply when processing is necessary to create and maintain your account, provide requested learning services, save progress, provide messages, calls, webinars or AI features, process purchases and deliver certificates, CVs, credits and rewards.",
        "Consent may apply to microphone, camera, photo and file access, voice recording or transcription, optional AI features, optional marketing communications or other processing where consent is legally required.",
        "You may withdraw consent through the app, device settings or by contacting us. Withdrawal does not affect processing completed lawfully before withdrawal.",
        "Legitimate interests may apply to protecting users and the service, preventing fraud and abuse, securing infrastructure, diagnosing problems, improving educational quality, maintaining records and protecting legal rights.",
        "We balance legitimate interests against your rights and reasonable expectations.",
        "Legal obligations may require processing or retention for tax, accounting, consumer-protection, payment, fraud-prevention, regulatory or valid legal-request purposes.",
      ],
    },
    {
      title: "6. AI processing and automated features",
      paragraphs: [
        "AI output may be incorrect, incomplete or inappropriate. Review important results before relying on them.",
        "AI learning scores, recommendations, rankings and level estimates are used for educational purposes.",
        "They are not intended to make legal, immigration, employment, financial, medical or similarly significant decisions about you.",
        "Some final-examination answers may be reviewed by authorized teachers or administrators rather than decided only by an automated system.",
      ],
      bullets: [
        "Generate educational answers.",
        "Translate or correct writing.",
        "Transcribe audio.",
        "Estimate language level.",
        "Identify strengths and areas for improvement.",
        "Recommend lessons or practice.",
        "Create CV content or formatting suggestions.",
      ],
    },
    {
      title: "7. How we share information",
      paragraphs: [
        "We do not sell personal information.",
        "We do not provide personal information to advertisers for unrelated cross-service behavioral advertising.",
        "We may share limited information with providers and authorized people where reasonably necessary to provide, secure and support Italir Pothe.",
      ],
      bullets: [
        "Hosting and infrastructure providers supporting application hosting, databases, file storage, content delivery, security, monitoring, email, SMS, backups and infrastructure.",
        "Firebase Cloud Messaging for push-notification tokens and related technical data.",
        "Google Play for payments, purchase verification, subscriptions, refunds, fraud prevention and transaction support.",
        "Agora for audio, video and connection information used during calls or webinars.",
        "LiveKit and configured AI, speech, transcription or voice providers for live audio, transcripts, prompts, conversation context and session information.",
        "Other users who receive information you intentionally share, including messages, attachments, profile details, call participation, webinar participation, leaderboard details and community messages.",
        "Authorized teachers, moderators and support staff who need information to review examinations, provide support, moderate content, investigate reports or manage purchases, certificates and rewards.",
        "Authorities or other parties where disclosure is required by law or reasonably necessary to protect safety, investigate fraud, enforce agreements or protect users and the public.",
        "Parties involved in a merger, acquisition, financing, restructuring or sale of assets, subject to appropriate notice and safeguards.",
      ],
    },
    {
      title: "8. Public certificate verification",
      paragraphs: [
        "Certificates may contain a verification code or public verification link.",
        "A person with a valid certificate identifier may be able to view limited information required to verify authenticity.",
        "Do not publicly share your certificate identifier unless you want other people to verify the certificate.",
      ],
      bullets: [
        "Certificate holder’s name.",
        "Certificate title.",
        "Associated course or examination.",
        "Issue date.",
        "Certificate status.",
        "Verification identifier.",
      ],
    },
    {
      title: "9. External services and links",
      paragraphs: [
        "When you open an external service, that provider may collect information under its own privacy policy.",
        "Italir Pothe does not control the provider’s independent processing.",
      ],
      bullets: [
        "Facebook pages or groups.",
        "WhatsApp support.",
        "External book stores.",
        "App stores.",
        "Other websites or communication services.",
      ],
    },
    {
      title: "10. Cookies and local device storage",
      paragraphs: [
        "The website and app may use cookies, secure storage, local storage or similar technology.",
        "We do not currently use third-party advertising SDKs in the Android application.",
        "This policy will be updated before such advertising technology is introduced.",
      ],
      bullets: [
        "Keep you signed in.",
        "Store authentication tokens.",
        "Remember language and app preferences.",
        "Maintain purchase-recovery information.",
        "Protect accounts and prevent fraud.",
        "Preserve necessary session information.",
      ],
    },
    {
      title: "11. Data retention",
      paragraphs: [
        "We retain information only for as long as reasonably necessary for the purposes described in this policy.",
        "Account and profile information is generally retained while the account is active.",
        "Learning progress, AI history and CV information may remain until deletion or until no longer needed.",
        "Purchase and accounting records may be retained for legally required periods.",
        "Security and diagnostic logs may be retained for a shorter operational period unless needed for investigation.",
        "Moderation and fraud records may be retained where necessary to protect users and prevent repeated abuse.",
        "Backup copies may remain temporarily until replaced through ordinary backup cycles.",
      ],
      bullets: [
        "Whether your account remains active.",
        "The type of information.",
        "Course, examination and certificate requirements.",
        "Purchase, refund or chargeback periods.",
        "Safety and fraud-prevention needs.",
        "Legal, tax and accounting obligations.",
        "Dispute and complaint periods.",
        "Backup and system-recovery cycles.",
      ],
    },
    {
      title: "12. Account and data deletion",
      paragraphs: [
        `You may request permanent account deletion inside the app through Settings → Delete Account, through the Italir Pothe public account-deletion webpage or by emailing ${supportEmail}.`,
        "We may verify your identity before completing the request.",
        "After a verified deletion request, we will delete or anonymize personal information associated with the account that is no longer necessary for legal, security, fraud-prevention or transaction-record purposes.",
        "Messages already delivered to another user may remain in that user’s conversation where necessary for conversation integrity, reporting or safety.",
        "Where reasonably possible, the deleted account’s identity will be removed or anonymized.",
        "Deleting an Italir Pothe account does not automatically cancel an active Google Play subscription. Subscriptions must be cancelled through Google Play.",
      ],
      bullets: [
        "Account and profile information.",
        "Learning progress.",
        "AI conversations and learning-memory information.",
        "CV information and generated files.",
        "Stored uploads.",
        "Device tokens.",
        "Available digital balances.",
        "Certificate personal information or public verification access, subject to legitimate recordkeeping requirements.",
        "Other account-associated service information.",
        "Limited tax and accounting records may be retained.",
        "Purchase, refund or chargeback records may be retained.",
        "Fraud, abuse-prevention and security records may be retained.",
        "Information required for legal compliance, disputes or enforcement of legal rights may be retained.",
      ],
    },
    {
      title: "13. Your choices and rights",
      paragraphs: [
        "Your available rights depend on the law that applies to you.",
        "You may update available profile information from Settings.",
        "You may control camera, microphone, notification, photo and file permissions through your device settings.",
        `To submit a privacy request, contact ${supportEmail}. We may request reasonable information to verify your identity and protect the account.`,
      ],
      bullets: [
        "Access personal information we hold about you.",
        "Correct inaccurate information.",
        "Delete your account and associated data.",
        "Request a copy of your information.",
        "Restrict certain processing.",
        "Object to processing based on legitimate interests.",
        "Request data portability.",
        "Withdraw consent.",
        "Opt out of optional marketing communications.",
        "Complain to an appropriate data-protection authority.",
      ],
    },
    {
      title: "14. International data processing",
      paragraphs: [
        "Italir Pothe and its service providers may process information in countries other than the country where you live.",
        "Where required, we use appropriate contractual, technical, organizational or legal safeguards for international transfers.",
        "Users in the European Economic Area may contact their local data-protection authority regarding unresolved privacy concerns.",
      ],
    },
    {
      title: "15. Security",
      paragraphs: [
        "We use reasonable administrative, technical and organizational measures designed to protect information.",
        "No application, website, transmission or storage system can guarantee absolute security.",
        "Keep passwords and one-time codes private.",
        `Contact ${supportEmail} immediately if you suspect unauthorized account access.`,
      ],
      bullets: [
        "Password hashing.",
        "Authenticated APIs.",
        "Secure token handling.",
        "Encrypted network transmission.",
        "Access controls.",
        "Restricted administrative permissions.",
        "Signed file-upload and download links where configured.",
        "Monitoring and security logging.",
        "Fraud and abuse controls.",
      ],
    },
    {
      title: "16. Children’s privacy",
      paragraphs: [
        "Italir Pothe is not intended for children under 13.",
        "Where applicable law requires a higher minimum age or parental permission, that higher requirement applies.",
        `A parent or guardian who believes that a child submitted personal information without appropriate authorization should contact ${supportEmail}. We will investigate and take appropriate action.`,
      ],
    },
    {
      title: "17. Changes to this policy",
      paragraphs: [
        "We may update this Privacy Policy when features, data practices, service providers, security requirements, applicable laws or Google Play requirements change.",
        "We will update the effective date.",
        "We will provide additional notice inside the app, by email or through another appropriate method when a material change requires notice.",
      ],
    },
    {
      title: "18. Contact us",
      paragraphs: [
        `For privacy questions, complaints, rights requests or account-deletion assistance, contact ${supportEmail}.`,
        "Include the email address or phone number connected to your account when relevant.",
        "Do not send your password or complete payment-card details.",
        "Italir Pothe",
      ],
    },
  ],
};

export const termsOfService: LegalDocument = {
  title: "Terms & Conditions",
  effectiveDate: "Effective July 23, 2026 · Last updated July 23, 2026",
  introduction:
    "These Terms and Conditions govern your access to and use of the Italir Pothe mobile application, website, backend services, courses, AI tools, messaging, calls, webinars, examinations, certificates, CV tools, purchases, rewards and related services. In these Terms, “Italir Pothe,” “we,” “us,” and “our” refer to the operator of the Italir Pothe service.",

  sections: [
    {
      title: "1. Acceptance of these Terms",
      paragraphs: [
        "By creating an account, accessing or using Italir Pothe, you agree to these Terms and the Italir Pothe Privacy Policy.",
        "Additional conditions may be displayed for a particular course, purchase, subscription, reward, examination or feature.",
        "If you do not agree, do not create an account or use the service.",
      ],
    },
    {
      title: "2. Eligibility",
      paragraphs: [
        "You must be at least 13 years old to independently create an account.",
        "If the law where you live requires a higher minimum age or parental permission, you may use the service only when that requirement has been satisfied.",
        "A parent or legal guardian who permits a minor to use Italir Pothe is responsible for supervising the minor’s use to the extent permitted by law.",
        "You must be legally capable of entering into these Terms.",
      ],
    },
    {
      title: "3. Your account",
      paragraphs: [
        "You are generally responsible for activity performed through your account unless applicable law provides otherwise.",
        "We may require email, phone or identity-related verification where reasonably necessary for account security, purchases, examinations, certificates, rewards or account deletion.",
      ],
      bullets: [
        "Provide accurate and current information.",
        "Maintain access to your verified email address or phone number.",
        "Keep your password and verification codes confidential.",
        "Use only your own account.",
        "Do not sell, transfer or share your account.",
        "Notify support promptly if you suspect unauthorized access.",
        "Keep profile and payment-related information updated.",
      ],
    },
    {
      title: "4. Description of the service",
      paragraphs: [
        "Italir Pothe is an educational platform designed primarily to help Bengali-speaking learners study the Italian language and related practical skills.",
        "Features may vary by account, region, device, course, purchase status, language, technical availability or product version.",
      ],
      bullets: [
        "Italian-language courses.",
        "Video, audio, vocabulary and theory lessons.",
        "Quizzes and practice activities.",
        "Daily challenges.",
        "Survival Italian.",
        "Career-track learning.",
        "AI Tutor text and voice features.",
        "Writing and translation assistance.",
        "Language-level assessment.",
        "Speaking, listening and writing examinations.",
        "Course certificates.",
        "CV creation and AI-assisted CV tools.",
        "Messaging and audio or video calls.",
        "Webinars.",
        "Leaderboards, XP, streaks and achievements.",
        "Digital and physical rewards.",
        "Course, subscription and digital-credit purchases.",
        "Public certificate verification.",
      ],
    },
    {
      title: "5. Educational and AI limitations",
      paragraphs: [
        "Italir Pothe is an educational service.",
        "AI-generated answers, translations, corrections, pronunciation feedback, transcripts, level estimates, CV suggestions and learning recommendations may be incomplete, inaccurate or inappropriate.",
        "You are responsible for reviewing important output before using or relying on it.",
        "Italir Pothe does not provide legal, immigration, medical, financial, employment, recruitment, government-certification or other regulated professional advice.",
        "Using Italir Pothe does not guarantee language fluency, examination success, employment, admission, visa or residency approval, certificate acceptance, official recognition or any particular educational or financial result.",
      ],
    },
    {
      title: "6. Courses and learning content",
      paragraphs: [
        "When you receive access to a course or learning product, Italir Pothe grants you a limited, personal, non-exclusive, non-transferable and revocable right to use that content for your own non-commercial learning.",
        "Course structures, lessons, instructors, availability and materials may be updated to improve quality or comply with legal and technical requirements.",
        "We will try to avoid materially reducing a paid product without reasonable justification.",
      ],
      bullets: [
        "Do not copy or redistribute complete courses.",
        "Do not resell access.",
        "Do not record or republish protected lessons without authorization.",
        "Do not share paid content publicly.",
        "Do not remove ownership notices.",
        "Do not use course content to create a competing product.",
        "Do not allow unauthorized users to access paid content through your account.",
      ],
    },
    {
      title: "7. Examinations and results",
      paragraphs: [
        "You must complete examinations honestly.",
        "Some answers may be assessed automatically. Speaking and writing answers may require teacher or administrator review.",
        "We may invalidate, correct or require review of an examination result where there is evidence of fraud, cheating, impersonation, manipulation, technical error, administrative error or another violation of these Terms.",
      ],
      bullets: [
        "Do not impersonate another learner.",
        "Do not submit answers completed by another person.",
        "Do not manipulate examination systems.",
        "Do not use unauthorized automation.",
        "Do not exploit technical errors.",
        "Do not submit false speaking recordings.",
        "Do not interfere with teacher review.",
        "Do not attempt to obtain unauthorized access to examination answers.",
      ],
    },
    {
      title: "8. Certificates",
      paragraphs: [
        "Certificate eligibility is determined by the requirements displayed for the relevant course or examination.",
        "A certificate confirms only the information displayed by Italir Pothe.",
        "It does not guarantee recognition by employers, government authorities, immigration authorities, educational institutions, professional organizations or other third parties.",
        "Certificates may contain public verification identifiers. Anyone with a valid identifier may be able to view limited certificate information.",
        "You are responsible for deciding whether to share your certificate or verification identifier.",
      ],
      bullets: [
        "We may correct, suspend, revoke or invalidate a certificate issued because of fraud.",
        "We may take action because of impersonation or cheating.",
        "We may take action following a payment reversal.",
        "We may correct administrative errors or incorrect information.",
        "We may revoke a certificate following a serious violation of these Terms.",
      ],
    },
    {
      title: "9. CV-generation services",
      paragraphs: [
        "You are responsible for ensuring that information included in your CV is accurate, lawful, not misleading, authorized for use and appropriate to share with employers or other recipients.",
        "AI-generated CV text may contain mistakes. Review every CV before downloading, submitting or publishing it.",
        "Italir Pothe does not guarantee employment, interview selection, employer decisions, compatibility with every recruitment system or acceptance of a particular format.",
        "You retain ownership of the personal information and original content you submit for your CV.",
      ],
    },
    {
      title: "10. Messages, calls and webinars",
      paragraphs: [
        "Communication features must be used lawfully and respectfully.",
        "Audio and video quality may depend on device capability, internet connection, service-provider availability, permissions and network restrictions.",
        "Messages, calls, reporting and blocking features are not emergency services. Contact the appropriate local emergency service when immediate assistance is required.",
      ],
      bullets: [
        "Do not harass, threaten or intimidate another person.",
        "Do not send spam or scams.",
        "Do not impersonate another person.",
        "Do not share private information without authorization.",
        "Do not send illegal, harmful or infringing content.",
        "Do not record or distribute another person’s voice or video without required consent.",
        "Do not use calls or webinars for unlawful activity.",
        "Do not disrupt webinars or learning sessions.",
        "Do not circumvent blocking or moderation features.",
      ],
    },
    {
      title: "11. User content",
      paragraphs: [
        "User content includes information you submit through messages, calls, webinar chat, examinations, AI prompts, reports, reviews, CV tools, profile photos, audio, images, documents and other uploads.",
        "You retain ownership of your original user content.",
        "You grant Italir Pothe a limited, worldwide, non-exclusive license to host, store, process, reproduce, transmit, adapt, moderate and display user content only as reasonably necessary to provide and secure the service.",
        "This license ends when the content is deleted, except where continued processing is reasonably necessary for legal obligations, safety, fraud prevention, dispute resolution, backup cycles or content already delivered to another user.",
      ],
      bullets: [
        "Deliver content to intended recipients.",
        "Generate requested AI output.",
        "Maintain security.",
        "Investigate reports.",
        "Enforce these Terms.",
        "Provide support.",
        "Improve service quality.",
        "You must have the necessary rights and permissions for submitted content.",
        "Your content must not violate the law or another person’s rights.",
        "Your content must not be knowingly false, malicious or harmful.",
      ],
    },
    {
      title: "12. Acceptable use",
      paragraphs: [
        "You must use Italir Pothe lawfully, honestly and respectfully.",
      ],
      bullets: [
        "Do not use Italir Pothe unlawfully.",
        "Do not harass, threaten, exploit or deceive anyone.",
        "Do not upload illegal, hateful, sexually exploitative, abusive or dangerous content.",
        "Do not exploit or endanger a child.",
        "Do not publish private information without permission.",
        "Do not infringe copyright, trademark or other intellectual-property rights.",
        "Do not upload malware or malicious code.",
        "Do not probe, scan or test security without written authorization.",
        "Do not circumvent authentication, payment or access controls.",
        "Do not reverse engineer restricted functionality except where law expressly permits it.",
        "Do not scrape protected content or user information.",
        "Do not use bots or unauthorized automation.",
        "Do not manipulate purchases, subscriptions, credits or refunds.",
        "Do not manipulate XP, streaks, rewards, rankings or referrals.",
        "Do not cheat in quizzes or examinations.",
        "Do not create fake accounts.",
        "Do not evade suspension or blocking.",
        "Do not use another person’s purchase token or account.",
        "Do not overload or interfere with servers, APIs, calls or webinars.",
        "Do not use AI features to facilitate unlawful or harmful activity.",
      ],
    },
    {
      title: "13. Reporting, blocking and moderation",
      paragraphs: [
        "Users may have access to reporting and blocking tools.",
        "We may use authorized personnel and automated systems to investigate suspected abuse and protect users and the service.",
        "Submitting intentionally false or malicious reports may itself violate these Terms.",
        "We do not guarantee that every report will result in removal or account action.",
      ],
      bullets: [
        "Review reports.",
        "Investigate suspected abuse.",
        "Remove or restrict content.",
        "Limit messaging or calling.",
        "Suspend features.",
        "Suspend or terminate accounts.",
        "Preserve evidence.",
        "Protect users and the service.",
      ],
    },
    {
      title: "14. Purchases and payment processing",
      paragraphs: [
        "Android purchases may be processed through Google Play.",
        "Google Play processes your payment method. Its payment, cancellation and refund terms may also apply.",
        "Italir Pothe may receive transaction information necessary to verify payment, grant access, manage subscriptions, process refunds and prevent fraud.",
      ],
      bullets: [
        "Product or package.",
        "Price.",
        "Currency.",
        "Taxes where applicable.",
        "Purchase type.",
        "Included benefits.",
        "Duration or renewal terms.",
        "Relevant restrictions.",
      ],
    },
    {
      title: "15. Subscriptions",
      paragraphs: [
        "When a product is described as a subscription, it may renew automatically until cancelled.",
        "You should cancel an active subscription through Google Play before deleting your account.",
      ],
      bullets: [
        "Renewal may be charged through Google Play.",
        "The renewal price and period are shown before confirmation.",
        "You are responsible for cancelling through Google Play before the next billing date.",
        "Removing the app does not automatically cancel a subscription.",
        "Deleting an Italir Pothe account does not automatically cancel a Google Play subscription.",
      ],
    },
    {
      title: "16. Refunds and payment reversals",
      paragraphs: [
        "Refund requests are handled according to Google Play rules, the terms displayed with the product and applicable consumer-protection law.",
        "Contact support if payment was completed but the purchased entitlement was not added to your account.",
      ],
      bullets: [
        "Access or entitlements may be removed when a transaction is refunded.",
        "Access may be removed when a transaction is cancelled or charged back.",
        "Access may be removed when a transaction is reversed or duplicated.",
        "Access may be removed when a transaction is unauthorized or fraudulent.",
        "Access may be removed when an entitlement was granted because of an error.",
      ],
    },
    {
      title: "17. Digital credits and rewards",
      paragraphs: [
        "Digital entitlements may include AI text tokens, AI voice time, CV credits, streak freezes, course access, subscription benefits, XP boosts, rewards and other app balances.",
        "Unless applicable law requires otherwise, digital entitlements are personal, non-transferable, not legal currency, have no cash value and cannot be exchanged between users.",
        "They may be removed following a refund, fraud, misuse or technical correction.",
        "Reward eligibility may depend on completion requirements, account status, stock, country, delivery availability and the rules displayed for the reward.",
        "For physical rewards, you must provide accurate delivery and contact information. Italir Pothe is not responsible for delivery failure caused by incorrect information provided by you.",
      ],
    },
    {
      title: "18. Device permissions",
      paragraphs: [
        "Some features require access to notifications, microphone, camera, photos, selected files or call-related Android functionality.",
        "Permissions are requested for the relevant feature.",
        "You may refuse or revoke optional permissions, but the related feature may stop working.",
        "You must not use microphone, camera or communication features to violate another person’s privacy or legal rights.",
      ],
    },
    {
      title: "19. Privacy",
      paragraphs: [
        "The Italir Pothe Privacy Policy explains what information is collected, why it is processed, how it is shared, how long it is retained, how account deletion works and what privacy rights may apply.",
        "By using a feature that requires personal information or device access, you acknowledge the relevant disclosure and permission request.",
      ],
    },
    {
      title: "20. Intellectual property",
      paragraphs: [
        "The Italir Pothe name, logos, software, designs, courses, lessons, videos, audio, books, learning materials, examinations, images, certificate designs, databases, branding and marketing materials are owned by Italir Pothe or its licensors.",
        "Except for the limited personal-use license granted by these Terms, no rights are transferred to you.",
        "You may not copy, sell, sublicense, publish, distribute or create unauthorized derivative works from protected Italir Pothe content.",
      ],
    },
    {
      title: "21. Third-party services",
      paragraphs: [
        "Italir Pothe may use or link to services operated by third parties.",
        "Third-party services operate under their own terms and privacy policies.",
        "To the extent permitted by law, Italir Pothe is not responsible for third-party content, availability, independent data practices, transactions, security incidents, policies or services outside our reasonable control.",
      ],
      bullets: [
        "Google Play.",
        "Firebase.",
        "Agora.",
        "LiveKit.",
        "AI, transcription and speech providers.",
        "Hosting and file-storage providers.",
        "Email and SMS providers.",
        "WhatsApp.",
        "Facebook.",
        "External book stores.",
      ],
    },
    {
      title: "22. Suspension and termination",
      paragraphs: [
        "We may warn, restrict, suspend or terminate access when reasonably necessary because of serious or repeated violations, fraud, abuse, security risk, payment reversal, unlawful conduct, harm to another person, cheating, system manipulation, legal requirements or protection of Italir Pothe and its users.",
        "Where appropriate, we may provide notice or an opportunity to appeal.",
        "Immediate action may be taken when necessary to address an urgent risk.",
      ],
    },
    {
      title: "23. Account deletion",
      paragraphs: [
        "You may stop using Italir Pothe at any time.",
        `You may request permanent account deletion from Settings inside the app, through the public account-deletion webpage or by contacting ${supportEmail}.`,
        "Identity verification may be required.",
        "Account deletion may permanently remove account access, learning progress, AI history, CV information, messages, unused digital balances, course access, rewards, examination history and certificate access.",
        "Certain limited records may be retained when necessary for legal compliance, security, payment records, fraud prevention or disputes, as explained in the Privacy Policy.",
        "Account deletion does not automatically cancel a Google Play subscription.",
      ],
    },
    {
      title: "24. Service availability",
      paragraphs: [
        "We work to provide a reliable service but do not guarantee uninterrupted availability.",
        "The service may be affected by maintenance, updates, network failures, device limitations, provider outages, security incidents, government restrictions or events outside our reasonable control.",
        "We may add, change, replace, limit or discontinue features.",
        "When a change materially affects a paid service, we will try to provide reasonable notice or an appropriate remedy where required by law.",
      ],
    },
    {
      title: "25. Disclaimers",
      paragraphs: [
        "To the maximum extent permitted by law, Italir Pothe is provided on an “as is” and “as available” basis.",
        "We do not guarantee that every feature will always be available, content will be error-free, AI output will be accurate, calls or webinars will be uninterrupted, every device will be compatible, learning will produce a particular result, certificates will be accepted, uploaded content will never be lost or security risks can be completely eliminated.",
        "Nothing in these Terms excludes rights or warranties that cannot legally be excluded.",
      ],
    },
    {
      title: "26. Limitation of liability",
      paragraphs: [
        "To the maximum extent permitted by applicable law, Italir Pothe and its service providers will not be liable for indirect, incidental, special, consequential, exemplary or punitive loss arising from use of or inability to use the service.",
        "This may include loss of data, profit, business, opportunity, expected savings or reputation.",
        "This limitation does not apply where liability cannot legally be excluded or limited, including mandatory consumer protections.",
      ],
    },
    {
      title: "27. Governing law and disputes",
      paragraphs: [
        "These Terms are governed by applicable law, including the laws of Bangladesh where applicable.",
        "Nothing in these Terms removes mandatory consumer or privacy rights available in the country where you live.",
        `Before beginning formal proceedings, you agree to contact ${supportEmail} and give us a reasonable opportunity to resolve the dispute informally.`,
        "An unresolved dispute may be brought before a court, tribunal or other body with lawful jurisdiction.",
      ],
    },
    {
      title: "28. Changes to these Terms",
      paragraphs: [
        "We may update these Terms when services, features, payment products, providers, security requirements, applicable laws or Google Play requirements change.",
        "We will update the effective date. Additional notice may be provided by email, notification or an in-app message when a material change requires notice.",
        "Continuing to use the service after updated Terms take effect means you accept the updated Terms, except where applicable law requires separate consent.",
      ],
    },
    {
      title: "29. General provisions",
      paragraphs: [
        "Entire agreement: These Terms, the Privacy Policy and any displayed product-specific terms form the agreement between you and Italir Pothe regarding the service.",
        "Severability: If one part of these Terms is found unenforceable, the remaining parts continue to apply.",
        "No waiver: Failure to enforce a provision does not waive the right to enforce it later.",
        "Assignment: You may not transfer your rights or obligations under these Terms without written permission. Italir Pothe may transfer its rights and obligations as part of a lawful restructuring, merger, acquisition or business transfer.",
        "Translations: Translations may be provided for convenience. To the extent permitted by applicable law, the English version controls when translations conflict. Mandatory rights under local-language consumer law remain unaffected.",
        "Survival: Provisions concerning payments, intellectual property, user content, disclaimers, liability, disputes and other provisions that should logically continue will survive account termination.",
      ],
    },
    {
      title: "30. Contact",
      paragraphs: [
        `Questions about these Terms may be sent to ${supportEmail}.`,
        "Italir Pothe",
      ],
    },
  ],
};
